# Form implementation generated from reading ui file 'main_window_new.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 541)
        MainWindow.setStyleSheet("background-color: rgb(124, 163, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.insurance_layout = QtWidgets.QVBoxLayout()
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 50, 191, 21))
        self.comboBox.setStyleSheet("background-color:rgb(103, 126, 255);")
        self.comboBox.setObjectName("comboBox")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 260, 551, 51))
        self.groupBox.setStyleSheet("background-color: rgb(103, 126, 255);")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setChecked(True)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 20, 141, 16))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")

        self.radioButtons = QtWidgets.QButtonGroup()
        self.radioButtons.addButton(self.radioButton, 1)
        self.radioButtons.addButton(self.radioButton_2, 2)

        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 100, 531, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 350, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 350, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.window_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.window_title.setGeometry(QtCore.QRect(90, 0, 461, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_title.sizePolicy().hasHeightForWidth())
        self.window_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.window_title.setFont(font)
        self.window_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.window_title.setObjectName("window_title")
        self.window_title_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.window_title_2.setGeometry(QtCore.QRect(110, 50, 181, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_title_2.sizePolicy().hasHeightForWidth())
        self.window_title_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.window_title_2.setFont(font)
        self.window_title_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.window_title_2.setObjectName("window_title_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Тип операции"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Выплачиваемые страховые взносы:"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.pushButton_2.setText(_translate("MainWindow", "Записать"))
        self.window_title.setText(_translate("MainWindow", "Калькулятор страховых взносов и заработной платы"))
        self.window_title_2.setText(_translate("MainWindow", "Должность:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
